##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "idman.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: idman-service
    app.kubernetes.io/component: idman
    app.kubernetes.io/part-of: {{ include "idman.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: idman-statefulset
    app.kubernetes.io/component: idman
    app.kubernetes.io/part-of: {{ include "idman.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.global.cenm.identityManager.internal.port }}
    targetPort: {{ .Values.global.cenm.identityManager.internal.port }}
    protocol: TCP
    name: issuance
  - port: {{ .Values.global.cenm.identityManager.revocation.port }}
    targetPort: {{ .Values.global.cenm.identityManager.revocation.port }}
    protocol: TCP
    name: revocation
  - port: {{ .Values.global.cenm.identityManager.port }}
    targetPort: {{ .Values.global.cenm.identityManager.port }}
    protocol: TCP
    name: main
  - port: {{ .Values.adminListener.port }}
    targetPort: {{ .Values.adminListener.port }}
    protocol: TCP
    name: adminlistener
