#helm install carrier-ca -f values/proxy-and-vault/peerOrganization/ca-server.yaml -n carrier-net fabric-ca-server
global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    address: http://vault.demo.com:8200
    authPath: carrier
    secretEngine: secretsv2
    secretPrefix: "data/carrier"
    imageSecretName: regcred
    tls: false

  cluster:
    provider: azure
    cloudNativeServices: false
    kubernetesUrl: https://kubernetes.url
  proxy:
    provider: haproxy
    externalUrlSuffix: test.yourdomain.com

cacerts:
  ca:
    orgName: carrier
    subject: /C=GB/ST=London/L=London/O=Carrier

server:
  tlsStatus: true
  admin: carrier-admin

settings:
  removeCertsOnDelete: true
