#helm install pee0 -f values/proxy-and-vault/peerOrganization/orderer.yaml -n carrier-net fabric-orderernode
global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    network: fabric
    address: http://vault.demo.com:8200
    authPath: carrier
    secretEngine: secretsv2
    secretPrefix: "data/carrier"

  cluster:
    provider: azure
    cloudNativeServices: false

  proxy:
    provider: haproxy
    externalUrlSuffix: test.yourdomain.com

catools:
  orgData:
    orgName: carrier
    type: peer
    componentSubject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
    certSubject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
    componentCountry: GB
    componentState: London
    componentLocation: London

  peers:
    - peer0-carrier

  users: 
    usersList:
      - user:
        identity: user1
        attributes:
        - key: "hf.Revoker"
          value: "true"
      - user:
        identity: user2
        attributes:
        - key: "hf.Revoker"
          value: "true"
    usersIdentities: 
      - user1
      - user2

cli:
  enabled: true
  orderer:
    address: orderer1.test.yourdomain.com:443
  network:
    version: 2.2.2
  peer:
    localMspId: carrierMSP
    tlsStatus: true
    address: carrier-net.test.yourdomain.com:443 

upgrade: False

peer:
  gossipPeerAddress: carrier-net.test.yourdomain.com:443
  gossipExternalEndpoint: carrier-net.test.yourdomain.com:443
  logLevel: info
  builder: hyperledger/fabric-ccenv:2.5.4
  couchdb:
    username: carrier-user

settings:
  removeConfigMapsOnDelete: true
  removeCertsOnDelete: true
  generateCertificates: true
