#helm install carrier-ca -f values/noproxy-and-novault/peerOrganization/ca-server.yaml -n carrier-net fabric-ca-server
global:
  serviceAccountName: vault-auth
  vault:
    type: kubernetes

  cluster:
    provider: azure
    cloudNativeServices: false
    kubernetesUrl: https://kubernetes.url
  
  proxy:
    provider: none
    externalUrlSuffix: carrier-net

cacerts:
  ca:
    orgName: carrier
    subject: /C=GB/ST=London/L=London/O=Carrier

server:
  tlsStatus: true
  admin: carrier-admin

settings:
  removeCertsOnDelete: true
