#helm install pee0-carrier -f values/noproxy-and-novault/peerOrganization/peer.yaml -n carrier-net fabric-peer
global:
  serviceAccountName: vault-auth
  vault:
    type: kubernetes

  cluster:
    provider: azure
    cloudNativeServices: false

  proxy:
    provider: "none"
    externalUrlSuffix: carrier-net

catools:
  orgData:
    orgName: carrier
    type: peer
    componentSubject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
    certSubject: O=Carrier/OU=Carrier/L=51.50,-0.13,London/C=GB
    componentCountry: GB
    componentState: London
    componentLocation: London

  peers:
    - peer0-carrier

  users: 
    usersList:
      - user:
        identity: user1
        attributes:
        - key: "hf.Revoker"
          value: "true"
      - user:
        identity: user2
        attributes:
        - key: "hf.Revoker"
          value: "true"
    usersIdentities: 
      - user1
      - user2

cli:
  enabled: true
  orderer:
    address: orderer1.supplychain-net:7050
  network:
    version: 2.5.4
  peer:
    localMspId: carrierMSP
    tlsStatus: true
    address: carrier-net:7051

upgrade: False

peer:
  gossipPeerAddress: carrier-net:7051
  gossipExternalEndpoint: carrier-net:7051
  logLevel: info
  builder: hyperledger/fabric-ccenv:2.5.4
  couchdb:
    username: carrier-user

settings:
  removeConfigMapsOnDelete: true
  removeCertsOnDelete: true
  generateCertificates: true
