##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "networkmap.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: networkmap-service
    app.kubernetes.io/component: networkmap
    app.kubernetes.io/part-of: {{ include "networkmap.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: networkmap-statefulset
    app.kubernetes.io/component: networkmap
    app.kubernetes.io/part-of: {{ include "networkmap.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.global.cenm.networkmap.internal.port }}
    targetPort: {{ .Values.global.cenm.networkmap.internal.port }}
    protocol: TCP
    name: http
  - port: {{ .Values.global.cenm.networkmap.port }}
    targetPort: {{ .Values.global.cenm.networkmap.port }}
    protocol: TCP
    name: http-external
  - port: {{ .Values.adminListener.port }}
    targetPort: {{ .Values.adminListener.port }}
    protocol: TCP
    name: adminlistener
