##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "node.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    app: {{ include "node.fullname" . }}
    app.kubernetes.io/name: node-statefulset
    app.kubernetes.io/component: node
    app.kubernetes.io/part-of: {{ include "node.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "node.fullname" . }}
      app.kubernetes.io/name: node-statefulset
      app.kubernetes.io/component: node
      app.kubernetes.io/part-of: {{ include "node.fullname" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/namespace: {{ .Release.Namespace }}
      app.kubernetes.io/release: {{ .Release.Name }}
  serviceName: {{ include "node.fullname" . }}
  volumeClaimTemplates: 
    - metadata:
        name: node-h2
      spec:
        storageClassName: storage-{{ .Release.Name }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.dbSize }}
  {{- if .Values.nodeConf.notary }}
    - metadata:
        name: notary-nodeinfo
      spec:
        storageClassName: storage-{{ .Release.Name }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
  {{- end }}
    - metadata:
        name: node-certificates
      spec:
        storageClassName: storage-{{ .Release.Name }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
    - metadata:
        name: node-cordapps
      spec:
        storageClassName: storage-{{ .Release.Name }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
    - metadata:
        name: node-logs
      spec:
        storageClassName: storage-{{ .Release.Name }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.size }}
  template:
    metadata:
      labels:
        app: {{ include "node.fullname" . }}
        app.kubernetes.io/name: node-statefulset
        app.kubernetes.io/component: node
        app.kubernetes.io/part-of: {{ include "node.fullname" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/namespace: {{ .Release.Namespace }}
        app.kubernetes.io/release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      hostname: {{ .Release.Name }}
      imagePullSecrets:
      {{- if .Values.image.pullSecret }}
        - name: {{ .Values.image.pullSecret }}
      {{- end }}  
      initContainers:
      - name: init-registration
        image: {{ .Values.image.node.repository }}:{{ .Values.image.node.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
        - |-
          bin/node-initial-registration.sh
        volumeMounts:
        - name: node-conf
          mountPath: /opt/corda/etc/node.conf
          subPath: node.conf
        - name: node-conf
          mountPath: /opt/corda/bin/node-initial-registration.sh
          subPath: node-initial-registration.sh
        - name: node-certificates
          mountPath: /opt/corda/certificates
      {{- if .Values.nodeConf.notary }}
        - name: notary-nodeinfo
          mountPath: /opt/corda/additional-node-infos
      {{- end }}
        - name: node-logs
          mountPath: /opt/corda/logs
        - name: node-h2
          mountPath: /opt/corda/h2
        - name: node-cordapps
          mountPath: /opt/corda/cordapps
        - name: cenm-certs
          mountPath: /certs
      - name: store-certs
        image: {{ .Values.image.bevelAlpine.repository }}:{{ .Values.image.bevelAlpine.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c"]
        args:
        - |-
        {{- if (eq .Values.global.vault.type "hashicorp") }}
          echo "Implement hashicorp releayed method"
        {{- else }}
          function safeWriteSecret {
            key=$1
            fpath=$2
            kubectl get secret ${key}-certs --namespace {{ .Release.Namespace }} -o json > /dev/null 2>&1
            if [ $? -ne 0 ]; then
              kubectl create secret generic ${key}-certs --namespace {{ .Release.Namespace }} \
                --from-file=nodekeystore.jks=${fpath}/nodekeystore.jks \
                --from-file=sslkeystore.jks=${fpath}/sslkeystore.jks \
                --from-file=truststore.jks=${fpath}/truststore.jks
            fi
          }
        {{- if .Values.nodeConf.notary }}
          function safeWriteNotaryNodeInfo {
            key=$1
            fpath=$2
            
            validating={{ .Values.nodeConf.notary.validating }}
            nodeInfoFile=$(basename $(ls ${fpath}/nodeInfo*))
            
            kubectl get secret ${key}-info --namespace {{ .Release.Namespace }} -o json > /dev/null 2>&1
            if [ $? -ne 0 ]
            then
              kubectl create secret generic ${key}-info --namespace {{ .Release.Namespace }} \
                --from-file=${nodeInfoFile}=${fpath}/${nodeInfoFile} \
                --from-literal=isValidating_${nodeInfoFile}=${validating} --save-config
            else
              ENCODED_NODEINFO_FILE=$(cat ${fpath}/${nodeInfoFile} | base64)
              # Retrieve the current secret, add the new key-value pair, and update the secret
              kubectl get secret ${key}-info -n {{ .Release.Namespace }} -o json | \
              jq --arg nodeinfo_key "${nodeInfoFile}" --arg value "$ENCODED_NODEINFO_FILE" \
              '.data[$nodeinfo_key]=$value' | kubectl apply -f -

              ENCODED_IS_VALIDATING=$(echo ${validating} | xargs | base64)

              kubectl get secret ${key}-info -n {{ .Release.Namespace }} -o json | \
              jq --arg isValidating_key "isValidating_${nodeInfoFile}" --arg value "$ENCODED_IS_VALIDATING" \
              '.data[$isValidating_key]=$value' | kubectl apply -f -              
            fi
          }
        {{- end }}
        {{- end }}
        {{- if and (ne .Values.global.cluster.provider "minikube") (.Values.global.cluster.cloudNativeServices) }}
          echo "Implement Cloud Native method"
        {{- else }}
          safeWriteSecret {{ .Release.Name }} /opt/corda/certificates
        {{- if .Values.nodeConf.notary }}
          safeWriteNotaryNodeInfo notary /opt/corda/additional-node-infos
        {{- end }}
        {{- end }}
          echo "Completed ..."
      {{- if (eq .Values.global.vault.type "hashicorp") }}
        env:
        - name: VAULT_ADDR
          value: "{{ .Values.global.vault.address }}"
        - name: VAULT_SECRET_ENGINE
          value: "{{ .Values.global.vault.secretEngine }}"
        - name: VAULT_SECRET_PREFIX
          value: "{{ .Values.global.vault.secretPrefix }}"
        - name: KUBERNETES_AUTH_PATH
          value: "{{ .Values.global.vault.authPath }}"
        - name: VAULT_APP_ROLE
          value: "{{ .Values.global.vault.role }}"
        - name: VAULT_TYPE
          value: "{{ .Values.global.vault.type }}"
      {{- end }}
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts/bevel-vault.sh
          subPath: bevel-vault.sh
      {{- if .Values.nodeConf.notary }}
        - name: notary-nodeinfo
          mountPath: /opt/corda/additional-node-infos
      {{- end }}
        - name: node-certificates
          mountPath: /opt/corda/certificates 
      - name: init-cordapps
        image: {{ .Values.image.bevelAlpine.repository }}:{{ .Values.image.bevelAlpine.tag }}
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args:
        - |-
          {{- if .Values.cordApps.getCordApps }}
            mkdir -p /tmp/downloaded-jars                      
            REPO_USER=$(cat /secret/username)
            REPO_USER_PASS=$(cat /secret/password)
            # Downloading official corda provided jars using curl 
            {{- range .Values.cordApps.jars }}
              cd /tmp/downloaded-jars && curl -u  $REPO_USER:$REPO_USER_PASS -O -L {{ .url }}
            {{- end }}
            cp -ar /tmp/downloaded-jars/* /opt/corda/cordapps
          {{- end }}  
        volumeMounts:
        - name: node-cordapps
          mountPath: /opt/corda/cordapps
        {{- if .Values.cordApps.mavenSecret }}
        - name: maven-secrets
          mountPath: "/secret"
        {{- end }}
      containers:
      - name: node
        image: {{ .Values.image.node.repository }}:{{ .Values.image.node.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
        - |-
          # running the node service
          bin/run.sh
        resources:
          limits:
            memory: 2G
          requests:
            memory: 1G
        ports:
        - containerPort: {{ .Values.nodeConf.p2pPort }}
          name: p2p
        livenessProbe:
          tcpSocket:
            port: {{ .Values.nodeConf.p2pPort }}
          initialDelaySeconds: 65
          periodSeconds: 30
        volumeMounts:
        - name: node-cordapps
          mountPath: /opt/corda/cordapps
        - name: cenm-certs
          mountPath: /certs
        - name: node-conf
          mountPath: /opt/corda/etc/node.conf
          subPath: node.conf
        - name: node-conf
          mountPath: /opt/corda/bin/run.sh
          subPath: run.sh
      {{- if .Values.nodeConf.notary }}
        - name: notary-nodeinfo
          mountPath: /opt/corda/additional-node-infos
      {{- end }}
        - name: node-certificates
          mountPath: /opt/corda/certificates
        - name: node-logs
          mountPath: /opt/corda/logs
        - name: node-h2
          mountPath: /opt/corda/h2
      - name: logs
        image: {{ .Values.image.node.repository }}:{{ .Values.image.node.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
        - |-
          cd /opt/corda
          while true; do tail -f logs/*.log 2>/dev/null; sleep 5; done
          # in case sth went wrong just wait indefinitely ...
          tail -f /dev/null
        volumeMounts:
        - name: node-logs
          mountPath: /opt/corda/logs
      volumes:
        - name: node-conf
          configMap:
            name: {{ include "node.fullname" . }}-conf
            defaultMode: 0777
        - name: cenm-certs
          secret:
            secretName: cenm-certs
        - name: scripts-volume
          configMap:
            name: bevel-vault-script
            defaultMode: 0777
        {{- if .Values.cordApps.mavenSecret }}
        - name: maven-secrets
          secret:
            secretName: {{ .Values.cordApps.mavenSecret }}
        {{- end }}
