#helm install orderer1 -f values/proxy-and-vault/ordererOrganization/orderer.yaml -n supplychain-net fabric-orderernode
global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    imageSecretName: regcred

  cluster:
    provider: azure
    cloudNativeServices: false

  proxy:
    provider: haproxy
    externalUrlSuffix: test.yourdomain.com

catools:
  orgData:
    orgName: supplychain
    type: orderer
    componentSubject: O=Orderer,L=51.50/-0.13/London,C=GB
    certSubject: O=Orderer/L=51.50,-0.13,London/C=GB
    componentCountry: UK
    componentState: London
    componentLocation: London
  
  orderers:
    - orderer1
    - orderer2
    - orderer3

network:
  version: 2.2.2

orderer:
  logLevel: info
  localMspId: supplychainMSP
  tlsstatus: true
  ordererAddress: orderer1.test.yourdomain.com:443

consensus:
  name: raft

settings:
  removeConfigMapsOnDelete: true
  removeCertsOnDelete: true
  generateCertificates: true
